name: djustin
description: A high-level Client Library for Justin Delivery Service OpenAPI
version: 0.2.0
homepage: https://github.com/masich/djustin

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
